import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../components/AboutMe'
import MySkills from '../components/MySkills'

const Home: NextPage = () => {
  return (
    <div className='flex flex-col gap-28'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MySkills />
      <AboutMe />
    </div>
  )
}

export default Home
